// Code generated by Kitex v0.5.1. DO NOT EDIT.

package analyseservice

import (
	analyse "LogAnalyse/app/shared/kitex_gen/analyse"
	common "LogAnalyse/app/shared/kitex_gen/common"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Analyse(ctx context.Context, req *analyse.AnalyseReq, callOptions ...callopt.Option) (r *common.NilResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAnalyseServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAnalyseServiceClient struct {
	*kClient
}

func (p *kAnalyseServiceClient) Analyse(ctx context.Context, req *analyse.AnalyseReq, callOptions ...callopt.Option) (r *common.NilResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Analyse(ctx, req)
}
